"""
DQN Training Script for Modality Selection

This script trains a DQN agent to select the optimal modality combination
at each time step to maximize cumulative reward (top-3 accuracy) over sequences.

State: cls_output from previous time step (embed_dim=512)
Action: Modality combination (0: only_pos, 1: missing_lidar, 2: missing_image, 3: full_observation)
Reward: accuracy_reward - lambda * modality_cost
        where accuracy_reward = 1 if top-3 correct, 0 otherwise
        and modality_cost is based on encoder FLOPs (pos=0.01, lidar=0.1, image=0.9)

Usage:
    python dqn_train.py --checkpoint ./checkpoints/best_model.pth

Author: Generated by Claude
"""

import os
import argparse
import random
from collections import deque, namedtuple
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from multimodal_dataset import MultiModalDataset
from multimodal_transformer import BeamPredictionModel


# Transition for replay buffer
Transition = namedtuple('Transition', ('state', 'action', 'reward', 'next_state', 'done'))

# Modality configurations (4 actions) - matches train.py
# Relative computation cost based on encoder FLOPs:
#   - Position encoder: ~0.5M FLOPs  -> cost = 0.01 (negligible)
#   - LiDAR encoder:    ~20M FLOPs   -> cost = 0.1
#   - Image encoder:    ~2.1G FLOPs  -> cost = 0.9
MODALITY_CONFIGS = [
    {'name': 'only_pos', 'use_pos': True, 'use_lidar': False, 'use_image': False, 'cost': 0.01},
    {'name': 'missing_lidar', 'use_pos': True, 'use_lidar': False, 'use_image': True, 'cost': 0.91},
    {'name': 'missing_image', 'use_pos': True, 'use_lidar': True, 'use_image': False, 'cost': 0.11},
    {'name': 'full_observation', 'use_pos': True, 'use_lidar': True, 'use_image': True, 'cost': 1.0},
]
NUM_ACTIONS = len(MODALITY_CONFIGS)


class DQN(nn.Module):
    """
    Deep Q-Network for modality selection.

    Input: cls_output (embed_dim=512)
    Output: Q-values for 4 actions (modality combinations)
    """

    def __init__(self, state_dim=512, num_actions=4, hidden_dim=256):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, num_actions),
        )

    def forward(self, state):
        return self.network(state)


class ReplayBuffer:
    """Experience replay buffer for DQN."""

    def __init__(self, capacity=100000):
        self.buffer = deque(maxlen=capacity)

    def push(self, *args):
        self.buffer.append(Transition(*args))

    def sample(self, batch_size):
        transitions = random.sample(self.buffer, batch_size)
        batch = Transition(*zip(*transitions))
        return batch

    def __len__(self):
        return len(self.buffer)


class ModalityEnv:
    """
    Environment for modality selection using a pre-trained BeamPredictionModel.

    For each sequence, the agent selects modalities at each time step.
    State is the cls_output from the previous prediction.
    Reward is 1 if the prediction is in top-3, 0 otherwise.
    """

    def __init__(self, beam_model, device):
        self.beam_model = beam_model
        self.device = device
        self.embed_dim = beam_model.embed_dim

        # Initial state (learnable or zero)
        self.initial_state = torch.zeros(1, self.embed_dim, device=device)

    @torch.no_grad()
    def get_cls_output(self, gps, lidar, image, action):
        """
        Get cls_output for a given modality configuration.

        Returns:
            cls_output: (1, embed_dim)
            logits: (1, num_classes)
        """
        config = MODALITY_CONFIGS[action]

        # Apply modality mask
        pos = gps if config['use_pos'] else None
        lidar_input = lidar if config['use_lidar'] else None
        image_input = image if config['use_image'] else None

        # Get batch size and device
        batch_size, device = self.beam_model._get_batch_size_and_device(pos, lidar_input, image_input)

        # Prepare CLS token
        cls_tokens = self.beam_model.cls_token.expand(batch_size, -1, -1) + self.beam_model.cls_type_embed

        # Encode each modality
        pos_tokens = self.beam_model.encode_position(pos, batch_size, device)
        lidar_tokens = self.beam_model.encode_lidar(lidar_input, batch_size, device)
        image_tokens = self.beam_model.encode_image(image_input, batch_size, device)

        # Concatenate
        tokens = torch.cat([cls_tokens, pos_tokens, lidar_tokens, image_tokens], dim=1)

        # Pass through transformer
        output = self.beam_model.transformer(tokens)

        # Extract CLS output
        cls_output = output[:, 0, :]  # (B, embed_dim)

        # Get logits
        logits = self.beam_model.classifier(cls_output)

        return cls_output, logits

    def compute_reward(self, logits, label, action, cost_lambda=0.1, top_k=3):
        """
        Compute reward based on top-k accuracy minus modality cost.

        Reward = accuracy_reward - cost_lambda * modality_cost

        Args:
            logits: (1, num_classes)
            label: int
            action: int (0-3)
            cost_lambda: float, weight for cost penalty
            top_k: int

        Returns:
            reward: float
            accuracy_reward: float (1.0 if correct in top-k, 0.0 otherwise)
        """
        _, pred_topk = logits.topk(top_k, dim=1)
        correct = (pred_topk == label).any().item()
        accuracy_reward = 1.0 if correct else 0.0

        # Modality cost penalty
        modality_cost = MODALITY_CONFIGS[action]['cost']
        reward = accuracy_reward - cost_lambda * modality_cost

        return reward, accuracy_reward


def parse_args():
    parser = argparse.ArgumentParser(description='DQN Training for Modality Selection')

    # Paths
    parser.add_argument('--checkpoint', type=str,
                        default='/home/changyuan/wireless_context/checkpoints/epoch_020.pth',
                        help='Path to pre-trained BeamPredictionModel checkpoint')
    parser.add_argument('--csv_path', type=str,
                        default='/home/changyuan/wireless_context/scenario9_dev/scenario9.csv',
                        help='Path to CSV file')
    parser.add_argument('--root_dir', type=str,
                        default='/home/changyuan/wireless_context/scenario9_dev',
                        help='Root directory for data files')
    parser.add_argument('--save_dir', type=str, default='./dqn_checkpoints',
                        help='Directory to save DQN checkpoints')

    # DQN hyperparameters
    parser.add_argument('--episodes', type=int, default=1000, help='Number of episodes')
    parser.add_argument('--batch_size', type=int, default=64, help='Batch size for DQN training')
    parser.add_argument('--gamma', type=float, default=0.99, help='Discount factor')
    parser.add_argument('--lr', type=float, default=1e-4, help='Learning rate')
    parser.add_argument('--epsilon_start', type=float, default=1.0, help='Initial epsilon')
    parser.add_argument('--epsilon_end', type=float, default=0.05, help='Final epsilon')
    parser.add_argument('--epsilon_decay', type=int, default=500, help='Epsilon decay episodes')
    parser.add_argument('--target_update', type=int, default=5, help='Target network update frequency')
    parser.add_argument('--buffer_size', type=int, default=1000, help='Replay buffer size')
    parser.add_argument('--hidden_dim', type=int, default=256, help='DQN hidden dimension')

    # Other
    parser.add_argument('--device', type=str, default='cuda', help='Device')
    parser.add_argument('--seed', type=int, default=42, help='Random seed')
    parser.add_argument('--log_interval', type=int, default=10, help='Log interval for running avg')
    parser.add_argument('--eval_interval', type=int, default=5, help='Evaluation interval (episodes)')
    parser.add_argument('--cost_lambda', type=float, default=0.1,
                        help='Weight for modality cost penalty in reward')

    return parser.parse_args()


def get_epsilon(episode, epsilon_start, epsilon_end, epsilon_decay):
    """Compute epsilon for epsilon-greedy policy."""
    return epsilon_end + (epsilon_start - epsilon_end) * np.exp(-episode / epsilon_decay)


def select_action(state, policy_net, epsilon, device):
    """Select action using epsilon-greedy policy."""
    if random.random() < epsilon:
        return random.randrange(NUM_ACTIONS)
    else:
        with torch.no_grad():
            q_values = policy_net(state)
            return q_values.argmax(dim=1).item()


class FixedPolicy(nn.Module):
    """Policy that always selects a fixed action."""
    def __init__(self, action):
        super().__init__()
        self.action = action

    def forward(self, state):
        return torch.zeros(state.size(0), NUM_ACTIONS, device=state.device).scatter_(
            1, torch.full((state.size(0), 1), self.action, device=state.device), 1.0
        )


class RandomPolicy(nn.Module):
    """Policy that selects actions uniformly at random."""
    def __init__(self):
        super().__init__()

    def forward(self, state):
        # Return uniform Q-values so argmax picks randomly
        return torch.rand(state.size(0), NUM_ACTIONS, device=state.device)


def optimize_model(policy_net, target_net, optimizer, replay_buffer, batch_size, gamma, device):
    """Perform one step of DQN optimization."""
    if len(replay_buffer) < batch_size:
        return None

    # Sample batch
    batch = replay_buffer.sample(batch_size)

    # Convert to tensors
    state_batch = torch.cat(batch.state)
    action_batch = torch.tensor(batch.action, device=device).unsqueeze(1)
    reward_batch = torch.tensor(batch.reward, device=device, dtype=torch.float32)
    next_state_batch = torch.cat(batch.next_state)
    done_batch = torch.tensor(batch.done, device=device, dtype=torch.float32)

    # Compute Q(s, a)
    q_values = policy_net(state_batch).gather(1, action_batch).squeeze(1)

    # Compute V(s') using target network
    with torch.no_grad():
        next_q_values = target_net(next_state_batch).max(1)[0]
        expected_q_values = reward_batch + gamma * next_q_values * (1 - done_batch)

    # Compute loss
    loss = F.smooth_l1_loss(q_values, expected_q_values)

    # Optimize
    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(policy_net.parameters(), 1.0)
    optimizer.step()

    return loss.item()


def run_episode(env, dataset, seq_indices, policy_net, epsilon, device,
                replay_buffer=None, training=True, cost_lambda=0.1, seq_idx=None):
    """
    Run one episode (one sequence) and collect transitions.

    Args:
        seq_idx: If provided, use this specific sequence. Otherwise randomly select.

    Returns:
        total_reward: float (with cost penalty)
        total_accuracy: float (pure top-k accuracy count)
        episode_length: int
        action_counts: dict
        total_cost: float
    """
    # Use specified sequence or randomly select
    if seq_idx is None:
        seq_idx = random.choice(seq_indices)

    # Get all windows for this sequence
    seq_windows = [(i, w) for i, w in enumerate(dataset.windows) if w[0] == seq_idx]

    if len(seq_windows) < 2:
        return 0.0, 0.0, 0, {}, 0.0

    # Sort by window indices to maintain temporal order
    seq_windows.sort(key=lambda x: x[1][1][0])  # Sort by first index in window

    total_reward = 0.0
    total_accuracy = 0.0
    total_cost = 0.0
    action_counts = {i: 0 for i in range(NUM_ACTIONS)}

    # Initial state
    state = env.initial_state.clone()

    for i, (dataset_idx, window_info) in enumerate(seq_windows):
        # Load data for this window
        sample = dataset[dataset_idx]
        gps = sample['gps'].unsqueeze(0).to(device)      # (1, 4, 2)
        lidar = sample['lidar'].unsqueeze(0).to(device)  # (1, 4, 216)
        lidar = lidar.unsqueeze(1)                        # (1, 1, 4, 216)
        image = sample['image'].unsqueeze(0).to(device)  # (1, 3, 540, 960)
        label = sample['label']

        # Select action
        action = select_action(state, policy_net, epsilon if training else 0.0, device)
        action_counts[action] += 1

        # Execute action and get next state
        next_state, logits = env.get_cls_output(gps, lidar, image, action)

        # Compute reward (with cost penalty)
        reward, accuracy_reward = env.compute_reward(logits, label, action, cost_lambda, top_k=3)
        total_reward += reward
        total_accuracy += accuracy_reward
        total_cost += MODALITY_CONFIGS[action]['cost']

        # Check if done (last step in sequence)
        done = (i == len(seq_windows) - 1)

        # Store transition
        if replay_buffer is not None and training:
            replay_buffer.push(state, action, reward, next_state, done)

        # Update state
        state = next_state

    return total_reward, total_accuracy, len(seq_windows), action_counts, total_cost


def evaluate(env, dataset, seq_indices, policy_net, device, cost_lambda=0.1):
    """
    Evaluate the policy on ALL test sequences (deterministic).

    Iterates through all sequences instead of random sampling to ensure
    consistent results for deterministic policies.
    """
    total_rewards = []
    total_accuracies = []
    total_lengths = []
    total_costs = []
    all_action_counts = {i: 0 for i in range(NUM_ACTIONS)}

    # Iterate through ALL sequences
    for seq_idx in seq_indices:
        reward, accuracy, length, action_counts, cost = run_episode(
            env, dataset, seq_indices, policy_net, 0.0, device,
            replay_buffer=None, training=False, cost_lambda=cost_lambda,
            seq_idx=seq_idx  # Use specific sequence
        )
        if length == 0:
            continue
        total_rewards.append(reward)
        total_accuracies.append(accuracy)
        total_lengths.append(length)
        total_costs.append(cost)
        for k, v in action_counts.items():
            all_action_counts[k] += v

    avg_reward = np.mean(total_rewards) if total_rewards else 0.0
    avg_accuracy = np.mean(total_accuracies) if total_accuracies else 0.0
    avg_length = np.mean(total_lengths) if total_lengths else 0.0
    avg_cost = np.mean(total_costs) if total_costs else 0.0
    avg_acc_per_step = avg_accuracy / avg_length if avg_length > 0 else 0
    avg_cost_per_step = avg_cost / avg_length if avg_length > 0 else 0

    return avg_reward, avg_acc_per_step, avg_cost_per_step, all_action_counts


def main():
    args = parse_args()

    # Set seed
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    # Device
    device = torch.device(args.device if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # Create save directory
    os.makedirs(args.save_dir, exist_ok=True)

    # ============== Load Pre-trained Model ==============
    print("\nLoading pre-trained BeamPredictionModel...")
    checkpoint = torch.load(args.checkpoint, map_location=device, weights_only=False)

    beam_model = BeamPredictionModel(
        embed_dim=checkpoint['args'].get('embed_dim', 512),
        num_heads=checkpoint['args'].get('num_heads', 8),
        num_layers=checkpoint['args'].get('num_layers', 6),
        num_classes=checkpoint['args'].get('num_classes', 64),
    )
    beam_model.load_state_dict(checkpoint['model_state_dict'])
    beam_model = beam_model.to(device)
    beam_model.eval()

    # Freeze beam model
    for param in beam_model.parameters():
        param.requires_grad = False

    print(f"Loaded model from epoch {checkpoint['epoch']}")

    # ============== Load Dataset ==============
    print("\nLoading dataset...")
    gps_stats = checkpoint.get('gps_stats', None)

    # train_dataset = MultiModalDataset(
    #     csv_path=args.csv_path,
    #     root_dir=args.root_dir,
    #     split='train',
    #     normalize_gps=True,
    #     gps_stats=gps_stats,
    # )

    train_dataset = MultiModalDataset(
        csv_path=args.csv_path,
        root_dir=args.root_dir,
        split='test',
        normalize_gps=True,
        gps_stats=gps_stats,
    )

    test_dataset = MultiModalDataset(
        csv_path=args.csv_path,
        root_dir=args.root_dir,
        split='test',
        normalize_gps=True,
        gps_stats=gps_stats,
    )

    # Get sequence indices
    train_seq_indices = list(set(w[0] for w in train_dataset.windows))
    test_seq_indices = list(set(w[0] for w in test_dataset.windows))

    train_seq_indices = train_seq_indices[:1]
    test_seq_indices = test_seq_indices[:1]

    print(f"Train sequences: {len(train_seq_indices)}")
    print(f"Test sequences: {len(test_seq_indices)}")

    # ============== Create Environment ==============
    env = ModalityEnv(beam_model, device)

    # ============== Create DQN ==============
    print("\nCreating DQN...")
    state_dim = beam_model.embed_dim

    policy_net = DQN(state_dim, NUM_ACTIONS, args.hidden_dim).to(device)
    target_net = DQN(state_dim, NUM_ACTIONS, args.hidden_dim).to(device)
    target_net.load_state_dict(policy_net.state_dict())
    target_net.eval()

    optimizer = optim.Adam(policy_net.parameters(), lr=args.lr)
    replay_buffer = ReplayBuffer(args.buffer_size)

    print(f"DQN parameters: {sum(p.numel() for p in policy_net.parameters()):,}")

    # ============== Pre-evaluate Fixed Baselines (only once) ==============
    print("\n" + "=" * 60)
    print("Evaluating Fixed Baseline Policies (one-time)")
    print("=" * 60)

    fixed_baseline_results = []
    for action_idx, config in enumerate(MODALITY_CONFIGS):
        fixed_policy = FixedPolicy(action_idx).to(device)
        fixed_reward, fixed_acc, fixed_cost, _ = evaluate(
            env, test_dataset, test_seq_indices, fixed_policy, device, args.cost_lambda
        )
        fixed_baseline_results.append((config['name'], fixed_reward, fixed_acc, fixed_cost))
        print(f"  {config['name']:<20}: Reward={fixed_reward:6.2f}, Top3={fixed_acc*100:5.2f}%, Cost={fixed_cost:.3f}")

    # ============== Training Loop ==============
    print("\n" + "=" * 60)
    print("Starting DQN Training")
    print(f"Cost lambda: {args.cost_lambda}")
    print(f"Eval interval: {args.eval_interval} episodes")
    print("=" * 60)

    best_eval_acc = -float('inf')
    episode_rewards = []
    episode_accuracies = []
    episode_costs = []

    # Setup logging to txt file
    log_path = os.path.join(args.save_dir, 'training_log.txt')
    with open(log_path, 'w') as f:
        f.write("episode,train_reward,train_top3_acc,train_cost,epsilon,loss,"
                "eval_reward,eval_top3_acc,eval_cost,action_only_pos,action_missing_lidar,"
                "action_missing_image,action_full_observation\n")

    for episode in range(1, args.episodes + 1):
        epsilon = get_epsilon(episode, args.epsilon_start, args.epsilon_end, args.epsilon_decay)

        # Run episode
        reward, accuracy, length, action_counts, cost = run_episode(
            env, train_dataset, train_seq_indices, policy_net, epsilon, device,
            replay_buffer=replay_buffer, training=True, cost_lambda=args.cost_lambda
        )
        episode_rewards.append(reward)
        episode_accuracies.append(accuracy / length if length > 0 else 0)
        episode_costs.append(cost / length if length > 0 else 0)

        # Optimize
        loss = optimize_model(
            policy_net, target_net, optimizer, replay_buffer,
            args.batch_size, args.gamma, device
        )

        # Update target network
        if episode % args.target_update == 0:
            target_net.load_state_dict(policy_net.state_dict())

        # Print every episode
        loss_str = f"{loss:.4f}" if loss is not None else "N/A"
        loss_val = loss if loss is not None else 0.0
        acc_per_step = accuracy / length if length > 0 else 0
        cost_per_step = cost / length if length > 0 else 0

        # Action distribution for this episode
        total_actions = sum(action_counts.values())
        action_str = ""
        if total_actions > 0:
            action_dist = [f"{MODALITY_CONFIGS[k]['name'][:8]}:{v}" for k, v in action_counts.items() if v > 0]
            action_str = " | " + ", ".join(action_dist)

        print(f"Ep {episode:4d}/{args.episodes} | "
              f"Reward: {reward:6.2f} | "
              f"Top3: {acc_per_step*100:5.1f}% | "
              f"Cost: {cost_per_step:.2f} | "
              f"Eps: {epsilon:.3f} | "
              f"Loss: {loss_str}{action_str}")

        # Periodic running average
        if episode % args.log_interval == 0:
            avg_reward = np.mean(episode_rewards[-args.log_interval:])
            avg_acc = np.mean(episode_accuracies[-args.log_interval:])
            avg_cost = np.mean(episode_costs[-args.log_interval:])
            print(f"  [AVG last {args.log_interval}] Reward: {avg_reward:.2f} | "
                  f"Top3: {avg_acc*100:.1f}% | Cost: {avg_cost:.2f} | Buffer: {len(replay_buffer)}")

        # Evaluation on test set every eval_interval episodes
        eval_reward, eval_acc_per_step, eval_cost_per_step = 0.0, 0.0, 0.0
        eval_action_pcts = [0.0, 0.0, 0.0, 0.0]

        if episode % args.eval_interval == 0:
            # Evaluate DQN policy
            eval_reward, eval_acc_per_step, eval_cost_per_step, eval_actions = evaluate(
                env, test_dataset, test_seq_indices, policy_net, device, args.cost_lambda
            )

            # Evaluate random policy (re-evaluate each time since it varies)
            random_policy = RandomPolicy().to(device)
            rand_reward, rand_acc, rand_cost, _ = evaluate(
                env, test_dataset, test_seq_indices, random_policy, device, args.cost_lambda
            )

            # Print comparison table (use cached fixed_baseline_results)
            print(f"\n  {'='*70}")
            print(f"  [EVAL @ Episode {episode}]")
            print(f"  {'-'*70}")
            print(f"  {'Policy':<20} | {'Reward':>8} | {'Top3 Acc':>8} | {'Cost':>8}")
            print(f"  {'-'*70}")
            for name, r, a, c in fixed_baseline_results:
                print(f"  {name:<20} | {r:>8.2f} | {a*100:>7.2f}% | {c:>8.3f}")
            print(f"  {'random':<20} | {rand_reward:>8.2f} | {rand_acc*100:>7.2f}% | {rand_cost:>8.3f}")
            print(f"  {'-'*70}")
            print(f"  {'DQN (ours)':<20} | {eval_reward:>8.2f} | {eval_acc_per_step*100:>7.2f}% | {eval_cost_per_step:>8.3f}")
            print(f"  {'='*70}")

            total_eval_actions = sum(eval_actions.values())
            if total_eval_actions > 0:
                eval_action_pcts = [eval_actions[k]/total_eval_actions*100 for k in range(NUM_ACTIONS)]
                eval_action_dist = {MODALITY_CONFIGS[k]['name']: f"{v/total_eval_actions*100:.1f}%"
                                   for k, v in eval_actions.items()}
                print(f"  DQN Actions: {eval_action_dist}\n")

            # Save best model (based on accuracy)
            if eval_acc_per_step > best_eval_acc:
                best_eval_acc = eval_acc_per_step
                save_path = os.path.join(args.save_dir, 'best_dqn.pth')
                torch.save({
                    'episode': episode,
                    'policy_net_state_dict': policy_net.state_dict(),
                    'target_net_state_dict': target_net.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'best_eval_acc': best_eval_acc,
                    'args': vars(args),
                }, save_path)
                print(f"  [NEW BEST] Top-3 Acc: {best_eval_acc*100:.2f}% - Saved to {save_path}")

        # Write to log file
        with open(log_path, 'a') as f:
            f.write(f"{episode},{reward:.4f},{acc_per_step*100:.2f},{cost_per_step:.4f},"
                    f"{epsilon:.4f},{loss_val:.4f},"
                    f"{eval_reward:.4f},{eval_acc_per_step*100:.2f},{eval_cost_per_step:.4f},"
                    f"{eval_action_pcts[0]:.2f},{eval_action_pcts[1]:.2f},"
                    f"{eval_action_pcts[2]:.2f},{eval_action_pcts[3]:.2f}\n")

    print(f"\nTraining log saved to: {log_path}")

    # ============== Final Evaluation ==============
    print("\n" + "=" * 60)
    print("Final Evaluation")
    print("=" * 60)

    # Load best model
    best_ckpt = torch.load(os.path.join(args.save_dir, 'best_dqn.pth'),
                           map_location=device, weights_only=False)
    policy_net.load_state_dict(best_ckpt['policy_net_state_dict'])

    # Evaluate on test set
    eval_reward, eval_acc_per_step, eval_cost_per_step, eval_actions = evaluate(
        env, test_dataset, test_seq_indices, policy_net, device,
        args.cost_lambda
    )

    print(f"\nTest Results (DQN Policy):")
    print(f"  Average Top-3 Accuracy: {eval_acc_per_step*100:.2f}%")
    print(f"  Average Modality Cost:  {eval_cost_per_step:.3f}")

    total_eval_actions = sum(eval_actions.values())
    print(f"\nAction Distribution:")
    for k, v in eval_actions.items():
        config_name = MODALITY_CONFIGS[k]['name']
        config_cost = MODALITY_CONFIGS[k]['cost']
        print(f"  {config_name:20s}: {v/total_eval_actions*100:5.1f}% (cost={config_cost:.2f})")

    # Compare with fixed and random policies
    print("\n" + "=" * 70)
    print("Comparison with Baseline Policies:")
    print("-" * 70)
    print(f"  {'Policy':<20} | {'Reward':>10} | {'Top3 Acc':>10} | {'Cost':>10}")
    print("-" * 70)

    for action_idx, config in enumerate(MODALITY_CONFIGS):
        fixed_policy = FixedPolicy(action_idx).to(device)
        fixed_reward, fixed_acc_per_step, fixed_cost_per_step, _ = evaluate(
            env, test_dataset, test_seq_indices, fixed_policy, device,
            args.cost_lambda
        )
        print(f"  {config['name']:20s} | {fixed_reward:>10.2f} | {fixed_acc_per_step*100:>9.2f}% | {fixed_cost_per_step:>10.3f}")

    # Random policy
    random_policy = RandomPolicy().to(device)
    rand_reward, rand_acc_per_step, rand_cost_per_step, _ = evaluate(
        env, test_dataset, test_seq_indices, random_policy, device,
        args.cost_lambda
    )
    print(f"  {'random':20s} | {rand_reward:>10.2f} | {rand_acc_per_step*100:>9.2f}% | {rand_cost_per_step:>10.3f}")

    print("-" * 70)
    print(f"  {'DQN (ours)':20s} | {eval_reward:>10.2f} | {eval_acc_per_step*100:>9.2f}% | {eval_cost_per_step:>10.3f}")
    print("=" * 70)

    # Save final model
    final_path = os.path.join(args.save_dir, 'final_dqn.pth')
    torch.save({
        'episode': args.episodes,
        'policy_net_state_dict': policy_net.state_dict(),
        'args': vars(args),
    }, final_path)
    print(f"\nFinal model saved to {final_path}")


if __name__ == '__main__':
    main()
