"""
MultiModal Transformer Encoder with Mask Token Mechanism

This module implements a multimodal fusion network that processes Position, LiDAR,
and Image modalities with support for missing modality handling via mask tokens.

Author: Generated by Claude
"""

import torch
import torch.nn as nn


class MultiModalTransformer(nn.Module):
    """
    Multi-modal Transformer encoder that fuses Position, LiDAR, and Image modalities.

    Supports missing modalities through learnable mask tokens that maintain
    sequence length consistency.

    Args:
        embed_dim: Embedding dimension (default: 512)
        num_heads: Number of attention heads (default: 8)
        num_layers: Number of transformer layers (default: 6)

    Input shapes:
        pos:   (B, 4, 2)       or None
        lidar: (B, 1, 4, 216)  or None
        image: (B, 3, 540, 960) or None

    Output shape: (B, 541, embed_dim) where 541 = 4 + 27 + 510
    """

    def __init__(self, embed_dim=512, num_heads=8, num_layers=6):
        super().__init__()
        self.embed_dim = embed_dim

        # Sequence lengths for each modality
        self.pos_seq_len = 4        # Position: 4 tokens
        self.lidar_seq_len = 27     # LiDAR: 1 * 27 = 27 tokens
        self.image_seq_len = 510    # Image: 17 * 30 = 510 tokens
        self.total_seq_len = self.pos_seq_len + self.lidar_seq_len + self.image_seq_len  # 541

        # ============== Modality Encoders ==============

        # Position encoder: (B, 40, 2) -> (B, 40, embed_dim)
        self.pos_encoder = nn.Sequential(
            nn.Linear(2, embed_dim // 2),
            nn.ReLU(),
            nn.Linear(embed_dim // 2, embed_dim),
        )

        # LiDAR encoder: (B, 1, 4, 216) -> (B, 27, embed_dim)
        # 3 Conv2d layers with stride=2: 4->2->1->1, 216->108->54->27
        self.lidar_encoder = nn.Sequential(
            nn.Conv2d(1, 64, kernel_size=3, stride=2, padding=1),      # -> (B, 64, 2, 108)
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),    # -> (B, 128, 1, 54)
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, embed_dim, kernel_size=3, stride=2, padding=1),  # -> (B, embed_dim, 1, 27)
            nn.BatchNorm2d(embed_dim),
            nn.ReLU(),
        )

        # Image encoder: (B, 3, 540, 960) -> (B, 510, embed_dim)
        # 4 Conv2d layers, total downsample /32, output (17, 30) feature map
        self.image_encoder = nn.Sequential(
            # Layer 1: stride=4 for initial aggressive downsampling
            # 540->135, 960->240
            nn.Conv2d(3, 64, kernel_size=7, stride=4, padding=3),      # -> (B, 64, 135, 240)
            nn.BatchNorm2d(64),
            nn.ReLU(),
            # Layer 2: stride=2, 135->68, 240->120
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),    # -> (B, 128, 68, 120)
            nn.BatchNorm2d(128),
            nn.ReLU(),
            # Layer 3: stride=2, 68->34, 120->60
            nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1),   # -> (B, 256, 34, 60)
            nn.BatchNorm2d(256),
            nn.ReLU(),
            # Layer 4: stride=2, 34->17, 60->30
            nn.Conv2d(256, embed_dim, kernel_size=3, stride=2, padding=1),  # -> (B, embed_dim, 17, 30)
            nn.BatchNorm2d(embed_dim),
            nn.ReLU(),
        )

        # ============== Mask Tokens (Learnable) ==============
        # Used when corresponding modality is missing
        self.pos_mask_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.lidar_mask_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.image_mask_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)

        # ============== Modality Type Embeddings ==============
        # Distinguish tokens from different modalities
        self.pos_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.lidar_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.image_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)

        # ============== Transformer Encoder ==============
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dim_feedforward=embed_dim * 4,
            dropout=0.1,
            activation='gelu',
            batch_first=True,
            norm_first=True,  # Pre-norm for better training stability
        )
        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers,
            norm=nn.LayerNorm(embed_dim),
        )

        # Initialize weights
        self._init_weights()

    def _init_weights(self):
        """Initialize weights for linear and conv layers."""
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def _get_batch_size_and_device(self, pos, lidar, image):
        """Extract batch size and device from non-None inputs."""
        if pos is not None:
            return pos.shape[0], pos.device
        elif lidar is not None:
            return lidar.shape[0], lidar.device
        elif image is not None:
            return image.shape[0], image.device
        else:
            raise ValueError("At least one modality must be provided!")

    def encode_position(self, pos, batch_size, device):
        """
        Encode position modality or generate mask tokens.

        Args:
            pos: (B, 4, 2) or None
            batch_size: int
            device: torch device

        Returns:
            pos_tokens: (B, 4, embed_dim)
        """
        if pos is not None:
            # Normal encoding: (B, 4, 2) -> (B, 4, embed_dim)
            pos_tokens = self.pos_encoder(pos)
        else:
            # Use mask token: expand to (B, 4, embed_dim)
            pos_tokens = self.pos_mask_token.expand(batch_size, self.pos_seq_len, -1).to(device)

        # Add modality type embedding
        pos_tokens = pos_tokens + self.pos_type_embed
        return pos_tokens

    def encode_lidar(self, lidar, batch_size, device):
        """
        Encode LiDAR modality or generate mask tokens.

        Args:
            lidar: (B, 1, 4, 216) or None
            batch_size: int
            device: torch device

        Returns:
            lidar_tokens: (B, 27, embed_dim)
        """
        if lidar is not None:
            # Conv encoding: (B, 1, 4, 216) -> (B, embed_dim, 1, 27)
            lidar_feat = self.lidar_encoder(lidar)
            # Flatten spatial dims: (B, embed_dim, 1, 27) -> (B, embed_dim, 27) -> (B, 27, embed_dim)
            lidar_tokens = lidar_feat.flatten(2).transpose(1, 2)
        else:
            # Use mask token: expand to (B, 27, embed_dim)
            lidar_tokens = self.lidar_mask_token.expand(batch_size, self.lidar_seq_len, -1).to(device)

        # Add modality type embedding
        lidar_tokens = lidar_tokens + self.lidar_type_embed
        return lidar_tokens

    def encode_image(self, image, batch_size, device):
        """
        Encode image modality or generate mask tokens.

        Args:
            image: (B, 3, 540, 960) or None
            batch_size: int
            device: torch device

        Returns:
            image_tokens: (B, 510, embed_dim)
        """
        if image is not None:
            # Conv encoding: (B, 3, 540, 960) -> (B, embed_dim, 17, 30)
            image_feat = self.image_encoder(image)
            # Flatten spatial dims: (B, embed_dim, 17, 30) -> (B, embed_dim, 510) -> (B, 510, embed_dim)
            image_tokens = image_feat.flatten(2).transpose(1, 2)
        else:
            # Use mask token: expand to (B, 510, embed_dim)
            image_tokens = self.image_mask_token.expand(batch_size, self.image_seq_len, -1).to(device)

        # Add modality type embedding
        image_tokens = image_tokens + self.image_type_embed
        return image_tokens

    def forward(self, pos=None, lidar=None, image=None):
        """
        Forward pass with support for missing modalities.

        Args:
            pos:   Position data,   shape (B, 4, 2)       or None
            lidar: LiDAR data,      shape (B, 1, 4, 216)  or None
            image: Image data,      shape (B, 3, 540, 960) or None

        Returns:
            output: Fused features, shape (B, 541, embed_dim)
                    where 541 = 4 (pos) + 27 (lidar) + 510 (image)
        """
        # Step 1: Get batch size and device from non-None input
        batch_size, device = self._get_batch_size_and_device(pos, lidar, image)

        # Step 2: Encode each modality (or use mask tokens if None)
        pos_tokens = self.encode_position(pos, batch_size, device)      # (B, 4, embed_dim)
        lidar_tokens = self.encode_lidar(lidar, batch_size, device)     # (B, 27, embed_dim)
        image_tokens = self.encode_image(image, batch_size, device)     # (B, 510, embed_dim)

        # Step 3: Concatenate all tokens
        # [pos_tokens, lidar_tokens, image_tokens] -> (B, 541, embed_dim)
        tokens = torch.cat([pos_tokens, lidar_tokens, image_tokens], dim=1)

        # Optional: Assert shape for debugging
        assert tokens.shape == (batch_size, self.total_seq_len, self.embed_dim), \
            f"Expected shape ({batch_size}, {self.total_seq_len}, {self.embed_dim}), got {tokens.shape}"

        # Step 4: Pass through Transformer encoder
        output = self.transformer(tokens)  # (B, 541, embed_dim)

        return output

    def get_modality_indices(self):
        """
        Get the index ranges for each modality in the output sequence.

        Returns:
            dict: {'pos': (0, 4), 'lidar': (4, 31), 'image': (31, 541)}
        """
        pos_end = self.pos_seq_len
        lidar_end = pos_end + self.lidar_seq_len
        image_end = lidar_end + self.image_seq_len

        return {
            'pos': (0, pos_end),
            'lidar': (pos_end, lidar_end),
            'image': (lidar_end, image_end),
        }


class BeamPredictionModel(nn.Module):
    """
    Beam Prediction Model for wireless communication.

    Uses MultiModalTransformer encoder with a CLS token for 64-class beam prediction.

    Architecture:
        1. CLS token prepended to the sequence
        2. MultiModalTransformer encoder processes [CLS, pos, lidar, image] tokens
        3. Classification head maps CLS output to 64 beam classes

    Args:
        embed_dim: Embedding dimension (default: 512)
        num_heads: Number of attention heads (default: 8)
        num_layers: Number of transformer layers (default: 6)
        num_classes: Number of beam classes (default: 64)
        dropout: Dropout rate for classification head (default: 0.1)

    Input shapes:
        pos:   (B, 4, 2)       or None
        lidar: (B, 1, 4, 216)  or None
        image: (B, 3, 540, 960) or None

    Output shape: (B, 64) - logits for each beam class
    """

    def __init__(self, embed_dim=512, num_heads=8, num_layers=6,
                 num_classes=64, dropout=0.1):
        super().__init__()
        self.embed_dim = embed_dim
        self.num_classes = num_classes

        # ============== CLS Token ==============
        # Learnable classification token prepended to sequence
        self.cls_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)

        # ============== Modality Encoders (same as MultiModalTransformer) ==============
        self.pos_seq_len = 4
        self.lidar_seq_len = 27
        self.image_seq_len = 510
        self.total_seq_len = 1 + self.pos_seq_len + self.lidar_seq_len + self.image_seq_len  # 542

        # Position encoder: (B, 4, 2) -> (B, 4, embed_dim)
        self.pos_encoder = nn.Sequential(
            nn.Linear(2, embed_dim // 2),
            nn.ReLU(),
            nn.Linear(embed_dim // 2, embed_dim),
        )

        # LiDAR encoder: (B, 1, 4, 216) -> (B, 27, embed_dim)
        self.lidar_encoder = nn.Sequential(
            nn.Conv2d(1, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, embed_dim, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(embed_dim),
            nn.ReLU(),
        )

        # Image encoder: (B, 3, 540, 960) -> (B, 510, embed_dim)
        self.image_encoder = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=7, stride=4, padding=3),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.Conv2d(256, embed_dim, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(embed_dim),
            nn.ReLU(),
        )

        # ============== Mask Tokens ==============
        self.pos_mask_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.lidar_mask_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.image_mask_token = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)

        # ============== Modality Type Embeddings ==============
        self.cls_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.pos_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.lidar_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)
        self.image_type_embed = nn.Parameter(torch.randn(1, 1, embed_dim) * 0.02)

        # ============== Transformer Encoder ==============
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dim_feedforward=embed_dim * 4,
            dropout=0.1,
            activation='gelu',
            batch_first=True,
            norm_first=True,
        )
        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers,
            norm=nn.LayerNorm(embed_dim),
        )

        # ============== Classification Head ==============
        # MLP: embed_dim -> embed_dim -> num_classes
        self.classifier = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(embed_dim, num_classes),
        )

        # Initialize weights
        self._init_weights()

    def _init_weights(self):
        """Initialize weights for linear and conv layers."""
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def _get_batch_size_and_device(self, pos, lidar, image):
        """Extract batch size and device from non-None inputs."""
        if pos is not None:
            return pos.shape[0], pos.device
        elif lidar is not None:
            return lidar.shape[0], lidar.device
        elif image is not None:
            return image.shape[0], image.device
        else:
            raise ValueError("At least one modality must be provided!")

    def encode_position(self, pos, batch_size, device):
        """Encode position modality or generate mask tokens."""
        if pos is not None:
            pos_tokens = self.pos_encoder(pos)
        else:
            pos_tokens = self.pos_mask_token.expand(batch_size, self.pos_seq_len, -1).to(device)
        return pos_tokens + self.pos_type_embed

    def encode_lidar(self, lidar, batch_size, device):
        """Encode LiDAR modality or generate mask tokens."""
        if lidar is not None:
            lidar_feat = self.lidar_encoder(lidar)
            lidar_tokens = lidar_feat.flatten(2).transpose(1, 2)
        else:
            lidar_tokens = self.lidar_mask_token.expand(batch_size, self.lidar_seq_len, -1).to(device)
        return lidar_tokens + self.lidar_type_embed

    def encode_image(self, image, batch_size, device):
        """Encode image modality or generate mask tokens."""
        if image is not None:
            image_feat = self.image_encoder(image)
            image_tokens = image_feat.flatten(2).transpose(1, 2)
        else:
            image_tokens = self.image_mask_token.expand(batch_size, self.image_seq_len, -1).to(device)
        return image_tokens + self.image_type_embed

    def forward(self, pos=None, lidar=None, image=None):
        """
        Forward pass for beam prediction.

        Args:
            pos:   Position data,   shape (B, 4, 2)       or None
            lidar: LiDAR data,      shape (B, 1, 4, 216)  or None
            image: Image data,      shape (B, 3, 540, 960) or None

        Returns:
            logits: Beam class logits, shape (B, 64)
        """
        # Get batch size and device
        batch_size, device = self._get_batch_size_and_device(pos, lidar, image)

        # Prepare CLS token: (1, 1, embed_dim) -> (B, 1, embed_dim)
        cls_tokens = self.cls_token.expand(batch_size, -1, -1) + self.cls_type_embed

        # Encode each modality
        pos_tokens = self.encode_position(pos, batch_size, device)      # (B, 4, embed_dim)
        lidar_tokens = self.encode_lidar(lidar, batch_size, device)     # (B, 27, embed_dim)
        image_tokens = self.encode_image(image, batch_size, device)     # (B, 510, embed_dim)

        # Concatenate: [CLS, pos, lidar, image] -> (B, 542, embed_dim)
        tokens = torch.cat([cls_tokens, pos_tokens, lidar_tokens, image_tokens], dim=1)

        # Pass through Transformer encoder
        output = self.transformer(tokens)  # (B, 542, embed_dim)

        # Extract CLS token output (first token)
        cls_output = output[:, 0, :]  # (B, embed_dim)

        # Classification head
        logits = self.classifier(cls_output)  # (B, num_classes)

        return logits

    def predict_proba(self, pos=None, lidar=None, image=None):
        """
        Get probability distribution over beam classes.

        Returns:
            probs: Beam class probabilities, shape (B, 64)
        """
        logits = self.forward(pos, lidar, image)
        return torch.softmax(logits, dim=-1)

    def predict(self, pos=None, lidar=None, image=None):
        """
        Get predicted beam index.

        Returns:
            pred: Predicted beam indices, shape (B,)
        """
        logits = self.forward(pos, lidar, image)
        return torch.argmax(logits, dim=-1)


if __name__ == "__main__":
    print("=" * 60)
    print("MultiModal Transformer Encoder Test")
    print("=" * 60)

    # Create encoder model
    encoder = MultiModalTransformer(embed_dim=512)

    # Print model info
    total_params = sum(p.numel() for p in encoder.parameters())
    trainable_params = sum(p.numel() for p in encoder.parameters() if p.requires_grad)
    print(f"\nEncoder Parameters: {total_params:,} total, {trainable_params:,} trainable")
    print(f"Sequence lengths: pos={encoder.pos_seq_len}, lidar={encoder.lidar_seq_len}, "
          f"image={encoder.image_seq_len}, total={encoder.total_seq_len}")
    print()

    # Test data
    batch_size = 2
    pos = torch.randn(batch_size, 4, 2)
    lidar = torch.randn(batch_size, 1, 4, 216)
    image = torch.randn(batch_size, 3, 540, 960)

    # Test encoder
    print("Test Encoder: All modalities present")
    out = encoder(pos, lidar, image)
    print(f"  Input:  pos={pos.shape}, lidar={lidar.shape}, image={image.shape}")
    print(f"  Output: {out.shape}")
    assert out.shape == (batch_size, 541, 512), f"Expected (2, 541, 512), got {out.shape}"
    print("  PASSED")
    print()

    print("=" * 60)
    print("Beam Prediction Model Test")
    print("=" * 60)

    # Create beam prediction model
    model = BeamPredictionModel(embed_dim=512, num_classes=64)

    # Print model info
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"\nBeamPredictionModel Parameters: {total_params:,} total, {trainable_params:,} trainable")
    print(f"Sequence length (with CLS): {model.total_seq_len}")
    print(f"Number of classes: {model.num_classes}")
    print()

    # Test 1: All modalities present
    print("Test 1: All modalities -> logits")
    logits = model(pos, lidar, image)
    print(f"  Input:  pos={pos.shape}, lidar={lidar.shape}, image={image.shape}")
    print(f"  Output logits: {logits.shape}")
    assert logits.shape == (batch_size, 64), f"Expected (2, 64), got {logits.shape}"
    print("  PASSED")
    print()

    # Test 2: Probability output
    print("Test 2: Probability distribution")
    probs = model.predict_proba(pos, lidar, image)
    print(f"  Output probs: {probs.shape}")
    print(f"  Sum of probs: {probs.sum(dim=-1)}")  # Should be [1.0, 1.0]
    assert probs.shape == (batch_size, 64), f"Expected (2, 64), got {probs.shape}"
    assert torch.allclose(probs.sum(dim=-1), torch.ones(batch_size)), "Probs should sum to 1"
    print("  PASSED")
    print()

    # Test 3: Prediction output
    print("Test 3: Beam prediction")
    pred = model.predict(pos, lidar, image)
    print(f"  Predicted beams: {pred}")
    assert pred.shape == (batch_size,), f"Expected ({batch_size},), got {pred.shape}"
    assert (pred >= 0).all() and (pred < 64).all(), "Predictions should be in [0, 63]"
    print("  PASSED")
    print()

    # Test 4: Missing modalities
    print("Test 4: Missing LiDAR")
    logits = model(pos, None, image)
    print(f"  Input:  pos={pos.shape}, lidar=None, image={image.shape}")
    print(f"  Output: {logits.shape}")
    assert logits.shape == (batch_size, 64)
    print("  PASSED")
    print()

    print("Test 5: Only Position")
    logits = model(pos, None, None)
    print(f"  Input:  pos={pos.shape}, lidar=None, image=None")
    print(f"  Output: {logits.shape}")
    assert logits.shape == (batch_size, 64)
    print("  PASSED")
    print()

    print("Test 6: Only Image")
    logits = model(None, None, image)
    print(f"  Input:  pos=None, lidar=None, image={image.shape}")
    print(f"  Output: {logits.shape}")
    assert logits.shape == (batch_size, 64)
    print("  PASSED")
    print()

    # Test with CrossEntropyLoss (simulating training)
    print("Test 7: Training simulation with CrossEntropyLoss")
    labels = torch.randint(0, 64, (batch_size,))
    criterion = nn.CrossEntropyLoss()
    logits = model(pos, lidar, image)
    loss = criterion(logits, labels)
    print(f"  Labels: {labels}")
    print(f"  Loss: {loss.item():.4f}")
    print("  PASSED")
    print()

    print("=" * 60)
    print("All tests passed!")
    print("=" * 60)
