"""
Training Script for Beam Prediction Model

This script trains the BeamPredictionModel using multimodal data (GPS, LiDAR, Image)
to predict beam indices for wireless communication.

Supports random modality dropout during training:
    1. Only Position:   pos, None, None
    2. Missing LiDAR:   pos, None, image
    3. Missing Image:   pos, lidar, None
    4. Full Observation: pos, lidar, image

Usage:
    python train.py --csv_path /path/to/csv --root_dir /path/to/data

Author: Generated by Claude
"""

import os
import argparse
import random
import time
from datetime import datetime

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

from multimodal_dataset import MultiModalDataset, create_dataloaders
from multimodal_transformer import BeamPredictionModel


# Modality configurations
MODALITY_CONFIGS = {
    'only_pos': {'use_pos': True, 'use_lidar': False, 'use_image': False},
    'missing_lidar': {'use_pos': True, 'use_lidar': False, 'use_image': True},
    'missing_image': {'use_pos': True, 'use_lidar': True, 'use_image': False},
    'full_observation': {'use_pos': True, 'use_lidar': True, 'use_image': True},
}


def apply_modality_dropout(gps, lidar, image, config):
    """
    Apply modality dropout based on configuration.

    Args:
        gps: (B, 4, 2) GPS data
        lidar: (B, 1, 4, 216) LiDAR data
        image: (B, 3, 540, 960) Image data
        config: dict with 'use_pos', 'use_lidar', 'use_image' keys

    Returns:
        pos, lidar, image (with None for dropped modalities)
    """
    pos_out = gps if config['use_pos'] else None
    lidar_out = lidar if config['use_lidar'] else None
    image_out = image if config['use_image'] else None
    return pos_out, lidar_out, image_out


def parse_args():
    parser = argparse.ArgumentParser(description='Train Beam Prediction Model')

    # Data paths
    parser.add_argument('--csv_path', type=str,
                        default='/home/changyuan/wireless_context/scenario9_dev/scenario9.csv',
                        help='Path to CSV file')
    parser.add_argument('--root_dir', type=str,
                        default='/home/changyuan/wireless_context/scenario9_dev',
                        help='Root directory for data files')

    # Training hyperparameters
    parser.add_argument('--batch_size', type=int, default=8, help='Batch size')
    parser.add_argument('--epochs', type=int, default=50, help='Number of epochs')
    parser.add_argument('--lr', type=float, default=1e-4, help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-4, help='Weight decay')
    parser.add_argument('--train_ratio', type=float, default=0.8, help='Train split ratio')

    # Model hyperparameters
    parser.add_argument('--embed_dim', type=int, default=512, help='Embedding dimension')
    parser.add_argument('--num_heads', type=int, default=8, help='Number of attention heads')
    parser.add_argument('--num_layers', type=int, default=6, help='Number of transformer layers')
    parser.add_argument('--num_classes', type=int, default=64, help='Number of beam classes')
    parser.add_argument('--dropout', type=float, default=0.1, help='Dropout rate')

    # Other settings
    parser.add_argument('--num_workers', type=int, default=4, help='DataLoader workers')
    parser.add_argument('--device', type=str, default='cuda', help='Device (cuda/cpu)')
    parser.add_argument('--save_dir', type=str, default='./checkpoints_2', help='Checkpoint directory')
    parser.add_argument('--log_interval', type=int, default=10, help='Log every N batches')

    return parser.parse_args()


def compute_accuracy(logits, labels, topk=(1, 3, 5)):
    """
    Compute top-k accuracy.

    Args:
        logits: (B, num_classes)
        labels: (B,)
        topk: tuple of k values

    Returns:
        dict of accuracies
    """
    maxk = max(topk)
    batch_size = labels.size(0)

    _, pred = logits.topk(maxk, dim=1, largest=True, sorted=True)
    pred = pred.t()  # (maxk, B)
    correct = pred.eq(labels.view(1, -1).expand_as(pred))  # (maxk, B)

    results = {}
    for k in topk:
        correct_k = correct[:k].reshape(-1).float().sum(0)
        results[f'top{k}'] = correct_k.item() / batch_size * 100

    return results


def train_one_epoch(model, dataloader, criterion, optimizer, device, epoch, log_interval):
    """Train for one epoch with random modality dropout."""
    model.train()

    total_loss = 0
    total_correct = 0
    total_samples = 0
    config_counts = {k: 0 for k in MODALITY_CONFIGS.keys()}

    start_time = time.time()
    config_names = list(MODALITY_CONFIGS.keys())

    for batch_idx, batch in enumerate(dataloader):
        # Move data to device
        gps = batch['gps'].to(device)           # (B, 4, 2)
        lidar = batch['lidar'].to(device)       # (B, 4, 216)
        image = batch['image'].to(device)       # (B, 3, 540, 960)
        labels = batch['label'].to(device)      # (B,)

        # Reshape lidar: (B, 4, 216) -> (B, 1, 4, 216)
        lidar = lidar.unsqueeze(1)

        # Random modality dropout: select one of the 3 configurations
        config_name = random.choice(config_names)
        config = MODALITY_CONFIGS[config_name]
        config_counts[config_name] += 1

        # Apply modality dropout
        pos, lidar_input, image_input = apply_modality_dropout(gps, lidar, image, config)

        # Forward pass
        optimizer.zero_grad()
        logits = model(pos=pos, lidar=lidar_input, image=image_input)

        # Compute loss
        loss = criterion(logits, labels)

        # Backward pass
        loss.backward()
        optimizer.step()

        # Statistics
        total_loss += loss.item() * labels.size(0)
        pred = logits.argmax(dim=1)
        total_correct += (pred == labels).sum().item()
        total_samples += labels.size(0)

        # Logging
        if (batch_idx + 1) % log_interval == 0:
            elapsed = time.time() - start_time
            print(f'  Epoch {epoch} | Batch {batch_idx + 1}/{len(dataloader)} | '
                  f'Loss: {loss.item():.4f} | '
                  f'Acc: {total_correct / total_samples * 100:.2f}% | '
                  f'Time: {elapsed:.1f}s')

    avg_loss = total_loss / total_samples
    avg_acc = total_correct / total_samples * 100

    # Print modality dropout statistics
    print(f'  Modality usage: ' + ', '.join([f'{k}: {v}' for k, v in config_counts.items()]))

    return avg_loss, avg_acc


@torch.no_grad()
def evaluate_with_config(model, dataloader, criterion, device, config):
    """Evaluate on validation/test set with a fixed modality configuration."""
    model.eval()

    total_loss = 0
    total_samples = 0
    all_logits = []
    all_labels = []

    for batch in dataloader:
        # Move data to device
        gps = batch['gps'].to(device)
        lidar = batch['lidar'].to(device)
        image = batch['image'].to(device)
        labels = batch['label'].to(device)

        # Reshape lidar: (B, 4, 216) -> (B, 1, 4, 216)
        lidar = lidar.unsqueeze(1)

        # Apply modality dropout for this evaluation config
        pos, lidar_input, image_input = apply_modality_dropout(gps, lidar, image, config)

        # Forward pass
        logits = model(pos=pos, lidar=lidar_input, image=image_input)

        # Compute loss
        loss = criterion(logits, labels)

        total_loss += loss.item() * labels.size(0)
        total_samples += labels.size(0)

        all_logits.append(logits)
        all_labels.append(labels)

    # Concatenate all predictions
    all_logits = torch.cat(all_logits, dim=0)
    all_labels = torch.cat(all_labels, dim=0)

    # Compute metrics
    avg_loss = total_loss / total_samples
    accuracies = compute_accuracy(all_logits, all_labels, topk=(1, 3, 5))

    return avg_loss, accuracies


@torch.no_grad()
def evaluate_all_configs(model, dataloader, criterion, device):
    """Evaluate on validation/test set for all modality configurations."""
    results = {}
    top1_values = []

    for config_name, config in MODALITY_CONFIGS.items():
        loss, accs = evaluate_with_config(model, dataloader, criterion, device, config)
        results[config_name] = {'loss': loss, 'accs': accs}
        top1_values.append(accs['top1'])

    avg_top1 = sum(top1_values) / len(top1_values) if top1_values else 0.0
    return results, avg_top1


def main():
    args = parse_args()

    # Print configuration
    print("=" * 60)
    print("Beam Prediction Model Training")
    print("=" * 60)
    print(f"\nConfiguration:")
    for key, value in vars(args).items():
        print(f"  {key}: {value}")
    print()

    # Device setup
    if args.device == 'cuda' and torch.cuda.is_available():
        device = torch.device('cuda')
        print(f"Using GPU: {torch.cuda.get_device_name(0)}")
    else:
        device = torch.device('cpu')
        print("Using CPU")
    print()

    # Create save directory
    os.makedirs(args.save_dir, exist_ok=True)

    # ============== Data Loading ==============
    print("Loading datasets...")

    train_loader, test_loader, gps_stats = create_dataloaders(
        csv_path=args.csv_path,
        root_dir=args.root_dir,
        batch_size=args.batch_size,
        train_ratio=args.train_ratio,
        num_workers=args.num_workers,
        normalize_gps=True,
    )

    print(f"\nTrain batches: {len(train_loader)}")
    print(f"Test batches: {len(test_loader)}")
    print()

    # ============== Model Setup ==============
    print("Creating model...")

    model = BeamPredictionModel(
        embed_dim=args.embed_dim,
        num_heads=args.num_heads,
        num_layers=args.num_layers,
        num_classes=args.num_classes,
        dropout=args.dropout,
    )
    model = model.to(device)

    # Print model info
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model parameters: {total_params:,} total, {trainable_params:,} trainable")
    print()

    # ============== Training Setup ==============
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    # Learning rate scheduler
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=args.epochs,
        eta_min=args.lr * 0.01,
    )

    # ============== Training Loop ==============
    print("=" * 60)
    print("Starting Training")
    print("=" * 60)

    best_acc = 0
    best_epoch = 0
    history = {
        'train_loss': [],
        'train_acc': [],
        'test_loss': [],
        'test_top1': [],
        'test_top3': [],
        'test_top5': [],
    }
    metrics_path = os.path.join(args.save_dir, 'test_metrics.txt')
    with open(metrics_path, 'w') as f:
        f.write("epoch,config,loss,top1,top3,top5,avg_top1,avg_top3,avg_top5\n")

    for epoch in range(1, args.epochs + 1):
        print(f"\nEpoch {epoch}/{args.epochs}")
        print("-" * 40)

        # Train
        train_loss, train_acc = train_one_epoch(
            model, train_loader, criterion, optimizer, device, epoch, args.log_interval
        )

        # Evaluate across all modality configs
        test_results, avg_top1 = evaluate_all_configs(
            model, test_loader, criterion, device
        )

        # Update scheduler
        scheduler.step()
        current_lr = scheduler.get_last_lr()[0]

        # Log results
        print(f"\n  Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%")
        for config_name, result in test_results.items():
            accs = result['accs']
            print(f"  Test ({config_name}) Loss: {result['loss']:.4f} | "
                  f"Top-1: {accs['top1']:.2f}% | "
                  f"Top-3: {accs['top3']:.2f}% | "
                  f"Top-5: {accs['top5']:.2f}%")
        print(f"  Test Avg Top-1 (4 configs): {avg_top1:.2f}%")
        avg_top3 = sum(
            r['accs']['top3'] for r in test_results.values()
        ) / len(test_results)
        avg_top5 = sum(
            r['accs']['top5'] for r in test_results.values()
        ) / len(test_results)
        print(f"  Test Avg Top-3 (4 configs): {avg_top3:.2f}%")
        print(f"  Test Avg Top-5 (4 configs): {avg_top5:.2f}%")
        print(f"  LR: {current_lr:.6f}")

        # Save history
        history['train_loss'].append(train_loss)
        history['train_acc'].append(train_acc)
        history['test_loss'].append(
            sum(r['loss'] for r in test_results.values()) / len(test_results)
        )
        history['test_top1'].append(avg_top1)
        history['test_top3'].append(
            sum(r['accs']['top3'] for r in test_results.values()) / len(test_results)
        )
        history['test_top5'].append(avg_top5)

        with open(metrics_path, 'a') as f:
            for config_name, result in test_results.items():
                accs = result['accs']
                f.write(
                    f"{epoch},{config_name},{result['loss']:.6f},"
                    f"{accs['top1']:.2f},{accs['top3']:.2f},{accs['top5']:.2f},"
                    f"{avg_top1:.2f},{avg_top3:.2f},{avg_top5:.2f}\n"
                )

        # Save checkpoint each epoch
        epoch_checkpoint = {
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'scheduler_state_dict': scheduler.state_dict(),
            'best_acc': best_acc,
            'args': vars(args),
            'gps_stats': gps_stats,
        }
        epoch_save_path = os.path.join(args.save_dir, f'epoch_{epoch:03d}.pth')
        torch.save(epoch_checkpoint, epoch_save_path)

        # Save best model
        if avg_top1 > best_acc:
            best_acc = avg_top1
            best_epoch = epoch

            checkpoint = {
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'scheduler_state_dict': scheduler.state_dict(),
                'best_acc': best_acc,
                'args': vars(args),
                'gps_stats': gps_stats,
            }
            save_path = os.path.join(args.save_dir, 'best_model.pth')
            torch.save(checkpoint, save_path)
            print(f"  [NEW BEST] Saved to {save_path}")

    # ============== Final Results ==============
    print("\n" + "=" * 60)
    print("Training Complete!")
    print("=" * 60)
    print(f"\nBest Test Top-1 Accuracy: {best_acc:.2f}% (Epoch {best_epoch})")
    print(f"Best Test Top-3 Accuracy: {max(history['test_top3']):.2f}%")
    print(f"Best Test Top-5 Accuracy: {max(history['test_top5']):.2f}%")

    # Save final checkpoint
    final_checkpoint = {
        'epoch': args.epochs,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'history': history,
        'args': vars(args),
        'gps_stats': gps_stats,
    }
    final_path = os.path.join(args.save_dir, 'final_model.pth')
    torch.save(final_checkpoint, final_path)
    print(f"\nFinal model saved to {final_path}")

    # ============== Final Evaluation ==============
    print("\n" + "=" * 60)
    print("Final Evaluation on Test Set")
    print("=" * 60)

    # Load best model for final evaluation
    best_checkpoint = torch.load(
        os.path.join(args.save_dir, 'best_model.pth'),
        map_location=device,
        weights_only=False,
    )
    model.load_state_dict(best_checkpoint['model_state_dict'])

    final_results, final_avg_top1 = evaluate_all_configs(
        model, test_loader, criterion, device
    )
    for config_name, result in final_results.items():
        accs = result['accs']
        print(f"\nTest ({config_name}) Loss: {result['loss']:.4f}")
        print(f"Top-1 Accuracy: {accs['top1']:.2f}%")
        print(f"Top-3 Accuracy: {accs['top3']:.2f}%")
        print(f"Top-5 Accuracy: {accs['top5']:.2f}%")
    final_avg_top3 = sum(
        r['accs']['top3'] for r in final_results.values()
    ) / len(final_results)
    final_avg_top5 = sum(
        r['accs']['top5'] for r in final_results.values()
    ) / len(final_results)
    print(f"\nTest Avg Top-1 (4 configs): {final_avg_top1:.2f}%")
    print(f"Test Avg Top-3 (4 configs): {final_avg_top3:.2f}%")
    print(f"Test Avg Top-5 (4 configs): {final_avg_top5:.2f}%")


if __name__ == '__main__':
    main()
